### ISSUE TITLE
Failed to load target driver: C0000034/80000108

### ISSUE THREAD

**Issue by rohybnol** [cutecatsandvirtualmachines/CheatDriver#1]
when trying to load "PreHvDriver.sys" it returns me 80000108 and when trying to load "CheatDriver.sys" it returns me C0000034
virtualization is enabled in bios, intel, what could be the issue?
also as I see the KdMapper macro, wouldnt there be a custom entry needed then? I tried to load with test sign rn.

**Comment by cutecatsandvirtualmachines** [comment]
You are tripping detection in prehvdriver.sys, it's an optional driver (read the docs) you can disable loading it with some small tweaks in TestLoader

**Comment by rohybnol** [comment]
no matter what I try CheatDriver.sys is always be:
Failed to load target driver: C0000034
I have enabled VMX/VT-d enabled in BIOS.
Driver blocklist disabled.
HVCI disabled.

**Comment by cutecatsandvirtualmachines** [comment]
You'll have to inspect the code for references to your NTSTATUS code and see what's up. It's probably an easy fix.

**Comment by rohybnol** [comment]
I dont have any other output then C0000034 which is object name not found which makes no sense
how did you load up the cheatdriver.sys, using the testloader or your own mapper/loader? I tried with ci option disable to load up.

**Comment by rohybnol** [comment]
Using your test loader has no success either:
```Hypervisor not loaded!
[-] invalid drv_buffer size
: No such file or directory
Failed to load pre-hv module: 0xffffffff
Failed loading SKLib driver
Ntoskrnl at: 0xfffff80709a00000
Callback at: 0x0
Press any key . . .
Callback is null, returning
Failed mapping identity
Press any key . . .
```

PreHvDriver/CheatDriver all in same directory as TestLoader.exe
yet it says invalid drv_buffer/no such file or directory?

**Comment by cutecatsandvirtualmachines** [comment]
There is a 99% chance you are running the test loader from vs debugger, which means no access to the other builded files since you are in the debug folder.

**Comment by rohybnol** [comment]
no dude as I said I setup everything correctly

**Comment by cutecatsandvirtualmachines** [comment]
Then you'll need to debug it yourself I'm not sure
