### ISSUE TITLE
DbgMsg stops working correctly and causes BSOD

### ISSUE THREAD

**Issue by Lafko** [cutecatsandvirtualmachines/CheatDriver#11]
Great job!

If uncomment ENABLE_EPT_PROTECTION
After `vmm::Virtualise();`
`KeIpiGenericCall((PKIPI_BROADCAST_WORKER)&SVM::Virtualise, 0);` - DbgMsg stops working correctly and causes BSOD
![devenv_wPusU91X0D](https://github.com/user-attachments/assets/15ec7fe9-0efc-4d77-9d6c-08db00c585b8)
![vmware_fJSZfViUdw](https://github.com/user-attachments/assets/d58876f1-7af3-4477-85c3-3c98230c188b)
Its hapend on AMD and Intel

**Comment by cutecatsandvirtualmachines** [comment]
Not a bug.

Code outside the EPT shadow cannot see nor interact with code inside, ntoskrnl APIs are included in this list.
Pass it an "heap" string and it'll work if you really need logging like that.
